Repository py-pdf/pypdf, pull requests merged in 2022-04, with the labels that each got.

#612 Fix formatWarning for filename without slash
  PyPDF2/utils.py
Labels: Bug

#569 Fixed extractText()-Not returning text with spaces
  PyPDF2/pdf.py
Labels: Bug, PdfFileReader

#522 Fix "invalid escape sequence" SyntaxError
  PyPDF2/generic.py
Labels: Bug

#486 Fix: Avoid error when printing warning in pythonw
  PyPDF2/pdf.py
Labels: Bug, PdfFileReader

#614 add alpha channel support fo png files
  Scripts/pdf-image-extractor.py
Labels: Tiny, Images

#599 Use setuptools instead of distutils
  setup.py
Labels: Tiny

#366 fix python3 compatibility
  Scripts/2-up.py
  Tests/tests.py
Labels: Bug, Tiny

#334 Update pdf.py PageObject.extractText()
  PyPDF2/pdf.py
Labels: Feature, PdfFileReader

#618 if not self.strict, ignore a /Prev entry with the value 0 in the trailer
  PyPDF2/pdf.py
  Tests/test_reader.py
Labels: Tiny, Robustness, needs-test

#575 Close File Descriptors
  Sample_Code/basic_merging.py
Labels: Tiny

#469 Add Scripts/booklet.py.
  Scripts/booklet.py
Labels: needs-discussion

#463 中文字符相关的编码错误 Error in Chinese character encoding
  PyPDF2/generic.py
  PyPDF2/utils.py
Labels: Bug, Tiny

#198 Using self.strict and checking objects with None value
  PyPDF2/pdf.py
Labels: Bug

#744 Fix title sometimes None
  PyPDF2/pdf.py
Labels: Bug, Tiny

#740 Improved performance and security for ContentStream_readInlineImage.
  PyPDF2/pdf.py
Labels: Security, Tiny

#359 Fix IndexError for getPage() of decryped file (Issue #327)
  PyPDF2/pdf.py
Labels: Bug, Tiny, soon

#567 readObjectHeader: Allow extra whitespace before "obj"
  PyPDF2/pdf.py
Labels: Tiny, Robustness, soon

#764 DOC: Working with annotations
  docs/index.rst
  docs/user/adding-pdf-annotations.md
  docs/user/reading-pdf-annotations.md
Labels: Documentation, soon

#240 When merging pages together, clip by trimBox, which would otherwise be ignored
  PyPDF2/pdf.py
Labels: Tiny

#405 BUG: Handle cases where decodeParms is an ArrayObject
  PyPDF2/filters.py
Labels: Bug, Tiny

#642 Fix reading more than last1K for EOF
  PyPDF2/pdf.py
Labels: Bug, PdfFileReader

#603 Fix zlib -5 error for corrupt files
  PyPDF2/filters.py
Labels: Bug

#414 Fix Linked Form Value Issue #398
  PyPDF2/pdf.py
Labels: Bug, Forms

#320 ENH: Extract document permissions
  PyPDF2/pdf.py
Labels: Feature

#412 BUG: Updated pdf fields don't show up when page is written
  PyPDF2/pdf.py
Labels: Bug, Forms

#785 DOC: Robustness
  README.md
  docs/index.rst
  docs/user/robustness.md
Labels: Documentation

#321 Make selenium-generated PDF readable
  PyPDF2/pdf.py
Labels: Bug, Tiny, needs-test

#803 ENH: Allow setting permission flags when encrypting
  PyPDF2/pdf.py
Labels: Feature

#806 BUG: Improve spacing for text extraction
  PyPDF2/pdf.py
  Resources/crazyones.txt
  Tests/test_reader.py
  Tests/test_workflows.py
  Tests/test_writer.py
Labels: Text Extraction

#339 Make PdfFileMerger.addBookmark() to behave life PdfFileWriters'
  PyPDF2/merger.py
  Tests/test_merger.py
Labels: PdfFileMerger, soon, Bookmarks

#788 Fix #297 : fix corruption in startxref or xref table
  PyPDF2/pdf.py
  Tests/test_reader.py
Labels: Bug, soon
