Repository py-pdf/pypdf, pull requests merged in 2022-12, with the labels that each got.

#1365 MAINT: Use 'page_number' instead of 'pagenum'
  PyPDF2/_merger.py
  PyPDF2/_reader.py
  PyPDF2/_writer.py
  docs/user/migration-1-to-2.md
  tests/test_generic.py
  tests/test_reader.py
  tests/test_writer.py
Labels: is-maintenance

#1469 ROB: Padding issue with AES encryption
  PyPDF2/_encryption.py
Labels: is-robustness-issue

#1467 MAINT: Consistent method keywords
  PyPDF2/_reader.py
  PyPDF2/_writer.py
Labels: soon

#1482 MAINT: position ➔ page_number in Merger.merge
  PyPDF2/_merger.py
  PyPDF2/_writer.py
  docs/user/migration-1-to-2.md
Labels: soon

#1437 MAINT: Refactor Fit / Zoom parameters
  PyPDF2/_merger.py
  PyPDF2/_reader.py
  PyPDF2/_writer.py
  PyPDF2/generic/__init__.py
  PyPDF2/generic/_annotations.py
  PyPDF2/generic/_data_structures.py
  PyPDF2/generic/_fit.py
  docs/index.rst
  docs/modules/Fit.rst
  tests/test_generic.py
  tests/test_merger.py
  tests/test_writer.py
Labels: soon

#1371 ENH: Add Cloning
  PyPDF2/_merger.py
  PyPDF2/_page.py
  PyPDF2/_protocols.py
  PyPDF2/_reader.py
  PyPDF2/_writer.py
  PyPDF2/generic/_base.py
  PyPDF2/generic/_data_structures.py
  PyPDF2/types.py
  docs/user/merging-pdfs.md
  resources/Seige_of_Vicksburg_Sample_OCR-crazyones-merged.pdf
  tests/test_generic.py
  tests/test_merger.py
  tests/test_writer.py
Labels: soon

#1495 DOC: Changed 'latest' for 'stable'
  README.md
Labels: nf-documentation

#1519 ENH: Add support for page labels
  pypdf/_page_labels.py
  pypdf/_protocols.py
  pypdf/_reader.py
  tests/test_page_labels.py
  tests/test_reader.py
Labels: is-feature

#1522 PERF: Help the specializing adpative interpreter
  pypdf/_cmap.py
  pypdf/_codecs/__init__.py
  pypdf/_reader.py
  pypdf/_writer.py
  pypdf/generic/_annotations.py
  pypdf/xmp.py
  tests/test_generic.py
Labels: nf-performance
