Repository py-pdf/pypdf, pull requests merged in 2022-09, with the labels that each got.

#1350 PI: Avoid string concatenation with large embedded base64-encoded images
  PyPDF2/generic/_utils.py
Labels: nf-performance

#1252 ENH: Addition of optional visitor-functions in extract_text()
  PyPDF2/_cmap.py
  PyPDF2/_page.py
  tests/test_page.py
Labels: workflow-text-extraction, is-feature

#1372 ROB: Cope with cmap from #1322
  PyPDF2/_cmap.py
Labels: is-robustness-issue
