Repository py-pdf/pypdf, pull requests merged in 2022-07, with the labels that each got.

#1026 ENH: Add PdfReader.xfa attribute
  PyPDF2/_reader.py
  tests/test_reader.py
Labels: is-feature

#1061 STY: DOC of compress_content_streams
  PyPDF2/_page.py
Labels: is-maintenance

#1060 ROB: Guard against None-value in _get_outlines
  PyPDF2/_reader.py
Labels: is-robustness-issue

#1066 BUG: Let Page.scale also scale the crop-/trim-/bleed-/artbox
  PyPDF2/_page.py
  PyPDF2/generic.py
Labels: is-bug

#1072 PI: Use iterative DFS in PdfWriter._sweep_indirect_references
  PyPDF2/_writer.py
  PyPDF2/generic.py
  resources/Seige_of_Vicksburg_Sample_OCR-crazyones-merged.pdf
  tests/test_merger.py
  tests/test_workflows.py
  tests/test_writer.py
Labels: nf-performance, PdfWriter

#1084 ENH: Extract Text Enhancement (whitespaces)
  PyPDF2/_cmap.py
  PyPDF2/_page.py
  tests/test_page.py
Labels: workflow-text-extraction

#1105 Prevent deduplication of PageObject
  PyPDF2/_page.py
Labels: soon

#1133 ROB : cope with invalid parent xref (#1089)
  PyPDF2/_reader.py
  tests/test_reader.py
Labels: is-robustness-issue

#1120 ENH: Add interface to annotations and AnnotationBuilder
  PyPDF2/_page.py
  PyPDF2/_writer.py
  PyPDF2/generic.py
  docs/index.rst
  docs/modules/AnnotationBuilder.rst
  docs/user/adding-pdf-annotations.md
  docs/user/annotation-line.png
  docs/user/free-text-annotation.png
  tests/test_generic.py
  tests/test_page.py
  tests/test_writer.py
Labels: is-feature

#1147 TST: Test CryptRC4 encryption class
  PyPDF2/filters.py
  tests/test_encryption.py
  tests/test_workflows.py
Labels: nf-testing

#1076 ROB: Handle outlines without destination
  PyPDF2/_merger.py
  PyPDF2/_reader.py
  resources/outline-without-title.pdf
  resources/outlines-with-invalid-destinations.pdf
  tests/test_reader.py
Labels: PdfReader, is-robustness-issue, soon

#1151 MAINT: Reduce PdfReader.read complexity
  PyPDF2/_reader.py
  tests/test_reader.py
Labels: is-maintenance

#1159 MAINT: Add diagnostic output to exception in read_from_stream
  PyPDF2/generic.py
Labels: is-maintenance

#1157 BUG: Ignore if '/Perms' verify failed
  PyPDF2/_encryption.py
Labels: is-bug

#1155 ROB: Cope with utf16 character for space calculation
  PyPDF2/_cmap.py
  tests/test_workflows.py
Labels: soon

#1156 MAINT: Consistent terminology for outline items
  PyPDF2/_merger.py
  PyPDF2/_reader.py
  PyPDF2/_utils.py
  PyPDF2/_writer.py
  PyPDF2/generic.py
  PyPDF2/types.py
  docs/user/extract-text.md
  tests/bench.py
  tests/test_generic.py
  tests/test_merger.py
  tests/test_reader.py
  tests/test_workflows.py
  tests/test_writer.py
Labels: soon, is-maintenance

#1175 ENH: Add orientation param for text_extraction (# 1071)
  PyPDF2/_page.py
  tests/test_workflows.py
Labels: soon
