Repository py-pdf/pypdf, pull requests merged in 2022-06, with the labels that each got.

#929 ExtractText2
  PyPDF2/_page.py
  resources/PdfWithXForm.pdf
  resources/crazyones.txt
  tests/test_page.py
  tests/test_workflows.py
Labels: Text Extraction

#924 Pubpub zz extract text
  PyPDF2/_adobe_glyphs.py
  PyPDF2/_page.py
  PyPDF2/generic.py
  resources/crazyones.txt
  tests/test_page.py
  tests/test_workflows.py
Labels: Text Extraction

#932 Fix some conversion errors on non conform PDF
  PyPDF2/_reader.py
  tests/test_reader.py
Labels: Robustness

#939 DOC: Elaborate on PDF text extraction difficulties
  docs/user/extract-text.md
Labels: Documentation

#947 ENH: Update glyphlist
  PyPDF2/_adobe_glyphs.py
Labels: Text Extraction

#949 TST: Ignore PdfReadWarning in benchmark
  tests/bench.py
Labels: Testing

#646 Optimize read_next_end_line
  PyPDF2/_reader.py
  PyPDF2/_utils.py
  tests/test_reader.py
  tests/test_utils.py
Labels: Performance

#986 PI: Remove b_ calls
  PyPDF2/_reader.py
  PyPDF2/_security.py
  PyPDF2/_utils.py
  PyPDF2/generic.py
Labels: Performance

#749 ENH: Add decrypt support for V5 and AES-128, AES-256 (R5 only)
  PyPDF2/_merger.py
  PyPDF2/_reader.py
  PyPDF2/encryption.py
  PyPDF2/errors.py
  requirements/ci.in
  requirements/ci.txt
  resources/encryption/enc0.pdf
  resources/encryption/enc1.pdf
  resources/encryption/enc2.pdf
  resources/encryption/enc3.pdf
  resources/encryption/enc4.pdf
  resources/encryption/enc5.pdf
  resources/encryption/enc6.pdf
  resources/encryption/enc7.pdf
  resources/encryption/enc8.pdf
  resources/encryption/enc9.pdf
  resources/encryption/enca.pdf
  resources/encryption/encb.pdf
  setup.cfg
  tests/test_encryption.py
  tests/test_reader.py
  tox.ini
Labels: Feature, Large, soon

#967 DEP: Rename names to be PEP8-compliant
  PyPDF2/_encryption.py
  PyPDF2/_security.py
  PyPDF2/_writer.py
  PyPDF2/filters.py
  PyPDF2/generic.py
  PyPDF2/xmp.py
  make_changelog.py
  tests/test_generic.py
  tests/test_xmp.py
Labels: soon

#1015 ENH: Support R6 decrypting
  PyPDF2/__init__.py
  PyPDF2/_encryption.py
  PyPDF2/_merger.py
  PyPDF2/_reader.py
  resources/encryption/enca.pdf
  resources/encryption/encb.pdf
  resources/encryption/r2-empty-password.pdf
  resources/encryption/r2-user-password.pdf
  resources/encryption/r3-empty-password.pdf
  resources/encryption/r3-user-password.pdf
  resources/encryption/r4-aes-user-password.pdf
  resources/encryption/r4-user-password.pdf
  resources/encryption/r5-empty-password.pdf
  resources/encryption/r5-owner-password.pdf
  resources/encryption/r5-user-password.pdf
  resources/encryption/r6-both-passwords.pdf
  resources/encryption/r6-empty-password.pdf
  resources/encryption/r6-owner-password.pdf
  resources/encryption/r6-user-password.pdf
  resources/encryption/unencrypted.pdf
  tests/test_encryption.py
  tests/test_reader.py
Labels: workflow-encryption, soon

#1023 DOC: Add CHANGELOG to the rendered docs
  .gitignore
  CHANGELOG.md
  docs/conf.py
  docs/index.rst
  docs/meta/faq.md
  make_changelog.py
Labels: nf-documentation

#207 PI: Check duplicate objects in writer._sweep_indirect_references
  PyPDF2/_writer.py
  PyPDF2/generic.py
Labels: nf-performance, PdfWriter, soon

#1030 MAINT: Handle XML error when reading XmpInformation
  PyPDF2/xmp.py
Labels: soon
