Repository py-pdf/pypdf, pull requests merged in 2023-04, with the labels that each got.

#1768 ROB: Capture UnicodeDecodeError at PdfReader.pdf_header
  pypdf/_reader.py
  tests/test_reader.py
Labels: is-robustness-issue

#1765 ENH: Add transform method to Transformation
  pypdf/_page.py
  tests/test_page.py
Labels: is-feature

#1806 DOC: Use append instead of add_page
  docs/user/forms.md
Labels: nf-documentation

#1808 TST: Fix PDF/A test
  tests/test_pdfa.py
Labels: is-pdf/a-compliance

#1818 MAINT: Prepare for adding AES enryption support
  pypdf/_encryption.py
  tests/test_encryption.py
Labels: workflow-encryption, is-maintenance
