Repository py-pdf/pypdf, pull requests merged in 2023-06, with the labels that each got.

#1859 ROB: Handle missing /Type entry in Page tree
  pypdf/_writer.py
  tests/test_page.py
Labels: is-robustness-issue

#1865 BUG: Ignore UTF-8 decode errors
  pypdf/generic/_utils.py
Labels: is-bug, soon

#1869 MAINT: Improve CHANGELOG generation script
  CHANGELOG.md
  make_changelog.py
Labels: Meta

#1854 ENH: Add set_data to EncodedStreamObject
  pypdf/generic/_data_structures.py
  tests/test_generic.py
Labels: soon

#1864 BUG : Generate static apparearance for fields
  pypdf/_reader.py
  pypdf/_writer.py
  pypdf/constants.py
  resources/FormTestFromOo.pdf
  tests/test_reader.py
  tests/test_writer.py
Labels: soon, workflow-forms

#1848 ENH: Extend images interface by returning an ImageFile(File) class
  pypdf/_page.py
  pypdf/_utils.py
  pypdf/filters.py
  tests/test_filters.py
  tests/test_page.py
Labels: soon

#1849 ENH: Add capability to replace image
  pypdf/_page.py
  pypdf/_utils.py
  tests/test_workflows.py
Labels: is-feature

#1850 ENH: Extraction of inline images
  pypdf/_page.py
  tests/test_workflows.py
Labels: soon

#1885 MAINT: Install pytest-socket in tox
  tox.ini
Labels: is-maintenance

#1834 BUG: Fix RGB FlateEncode Images(PNG) and transparency
  pypdf/_page.py
  pypdf/_utils.py
  pypdf/constants.py
  pypdf/filters.py
  requirements/ci-3.11.txt
  tests/test_filters.py
  tests/test_page.py
  tests/test_workflows.py
Labels: is-bug, soon

#1861 DOC: Add details how to write metadata
  docs/user/metadata.md
Labels: nf-documentation

#1858 BUG: Append pdf with named destination using numbers for pages
  pypdf/_writer.py
  tests/test_writer.py
Labels: soon

#1917 MAINT: Prepare for adding AES support via #1816
  pypdf/_encryption.py
  pypdf/generic/_base.py
  tests/test_encryption.py
Labels: is-maintenance

#1913 BUG : cascaded filters in image objects
  pypdf/filters.py
  tests/test_filters.py
Labels: soon

#1843 ENH: Add page deletion feature to PdfWriter
  pypdf/_page.py
  pypdf/_writer.py
  tests/test_page.py
Labels: is-feature
