Repository py-pdf/pypdf, pull requests merged in 2023-08, with the labels that each got.

#2068 PI: optimize _decode_png_prediction
  pypdf/filters.py
Labels: soon

#2047 BUG: Writing German characters into form fields
  pypdf/_cmap.py
  pypdf/_writer.py
  tests/test_writer.py
Labels: soon

#2060 BUG: Fix incorrect tm_matrix in call to visitor_text
  pypdf/_page.py
  pypdf/_text_extraction/__init__.py
  resources/inkscape-abc.pdf
  tests/test_text_extraction.py
Labels: soon

#2093 SEC: Avoid endless recursion of reading damaged PDF file
  pypdf/_reader.py
  tests/test_reader.py
Labels: nf-security

#2097 MAINT: Make ParseError inherit from PyPdfError
  pypdf/errors.py
Labels: soon

#2100 MAINT: ContentType._data setter uses only bytes
  pypdf/_reader.py
  pypdf/_writer.py
  pypdf/filters.py
  pypdf/generic/_base.py
  pypdf/generic/_data_structures.py
Labels: soon

#2101 PI: Re-use content stream
  pypdf/_page.py
Labels: nf-performance

#2086 PI: Making pypdf as fast as pdfrw
  pypdf/_cmap.py
  pypdf/_encryption.py
  pypdf/_page.py
  pypdf/_writer.py
  pypdf/generic/_data_structures.py
  tests/__init__.py
  tests/test_generic.py
  tests/test_utils.py
  tests/test_writer.py
Labels: nf-performance, soon
