Repository py-pdf/pypdf, pull requests merged in 2023-02, with the labels that each got.

#1563 BUG: Replace decimal by float
  pypdf/generic/_base.py
  pypdf/generic/_rectangle.py
  resources/Seige_of_Vicksburg_Sample_OCR-crazyones-merged.pdf
  stream.pdf
  tests/test_generic.py
  tests/test_writer.py
Labels: nf-performance

#1647 DOC: merge_transformed_page()
  docs/user/add-watermark.md
  docs/user/cropping-and-transforming.md
  docs/user/nup-dest1.png
  docs/user/nup-dest2.png
  docs/user/nup-source.png
Labels: nf-documentation, workflow-merge

#1611 ENH : complete attachments functions (get/add)
  pypdf/_reader.py
  pypdf/_writer.py
  tests/test_writer.py
Labels: is-feature

#1641 BUG: Invalid font pointed during merge_resources
  pypdf/_page.py
  tests/test_page.py
Labels: is-bug

#1658 ROB: Improve tolerance to invalid Names/Dests
  pypdf/_reader.py
  tests/test_reader.py
Labels: PdfReader, is-robustness-issue

#1648 ENH: Add PdfWriter.remove_objects_from_page(page: PageObject, to_delete: ObjectDeletionFlag)
  pypdf/__init__.py
  pypdf/_writer.py
  tests/test_writer.py
Labels: is-robustness-issue, soon
