Repository py-pdf/pypdf, pull requests merged in 2023-05, with the labels that each got.

#1844 BUG: Accept XYZ destination with zoom missing (default to zoom=0.0)
  pypdf/generic/_data_structures.py
  tests/test_generic.py
Labels: is-bug

#1837 DOC: Add comparison with pdfplumber
  docs/meta/comparisons.md
Labels: nf-documentation

#1845 ROB: Handle missing /Type entry in Page tree
  pypdf/_reader.py
  tests/test_page.py
Labels: is-robustness-issue, soon
