Repository py-pdf/pypdf, pull requests merged in 2023-10, with the labels that each got.

#2228 BUG: Encrypt / decrypt Stream object dictionaries
  pypdf/_encryption.py
  tests/test_encryption.py
Labels: soon

#2254 DEV: Use pytest-xdist
  .github/workflows/github-ci.yaml
  pyproject.toml
  requirements/ci-3.11.txt
  requirements/ci.in
  requirements/ci.txt
  requirements/dev.txt
Labels: nf-ci

#2264 BUG: Infinite recursion when using PdfWriter(clone_from=reader)
  pypdf/generic/_data_structures.py
Labels: is-bug, nf-security

#2214 ENH: Add parameter to select images to be removed
  pypdf/__init__.py
  pypdf/_writer.py
  pypdf/constants.py
  tests/test_writer.py
Labels: soon
