Repository py-pdf/pypdf, pull requests merged in 2023-07, with the labels that each got.

#1933 BUG: PdfReader.get_fields() attempts to delete non-existing index "/Off"
  pypdf/_reader.py
Labels: is-bug

#1970 DEV: Automate the release process
  .github/workflows/github-ci.yaml
  .github/workflows/release.yaml
Labels: help wanted

#1984 BUG: Decode Black only/CMYK deviceN images
  pypdf/constants.py
  pypdf/filters.py
  tests/test_filters.py
Labels: soon

#2000 ENH: Use `cryptography` for encryption/decryption as a fallback for PyCryptodome
  .github/workflows/github-ci.yaml
  pypdf/_crypt_providers/__init__.py
  pypdf/_crypt_providers/_base.py
  pypdf/_crypt_providers/_cryptography.py
  pypdf/_crypt_providers/_fallback.py
  pypdf/_crypt_providers/_pycryptodome.py
  pypdf/_encryption.py
  pyproject.toml
  tests/test_encryption.py
Labels: soon

#1745 MAINT: Cleanup of annotations
  docs/index.rst
  docs/modules/AnnotationBuilder.rst
  docs/modules/annotations.rst
  docs/user/adding-pdf-annotations.md
  pypdf/_writer.py
  pypdf/annotations/__init__.py
  pypdf/annotations/_base.py
  pypdf/annotations/_markup_annotations.py
  pypdf/annotations/_non_markup_annotations.py
  pypdf/constants.py
  pypdf/generic/__init__.py
  pypdf/generic/_annotations.py
  tests/test_annotations.py
  tests/test_generic.py
  tests/test_writer.py
Labels: soon

#2007 BUG: Process /Separation ColorSpace
  pypdf/filters.py
  tests/test_filters.py
Labels: soon

#2012 BUG: Add RunLengthDecode filter
  pypdf/filters.py
  tests/test_filters.py
Labels: soon
