Repository py-pdf/pypdf, pull requests merged in 2023-03, with the labels that each got.

#1624 ROB: Allow merging the same page multiple times with annotations
  pypdf/_page.py
  pypdf/generic/_base.py
  pypdf/generic/_data_structures.py
  tests/test_page.py
Labels: soon

#1657 TST: Replace pytest.mark.external by enable_socket
  docs/dev/testing.md
  pyproject.toml
  requirements/ci-3.11.txt
  requirements/ci.in
  requirements/ci.txt
  tests/test_cmap.py
  tests/test_filters.py
  tests/test_generic.py
  tests/test_merger.py
  tests/test_page.py
  tests/test_page_labels.py
  tests/test_reader.py
  tests/test_utils.py
  tests/test_workflows.py
  tests/test_writer.py
  tests/test_xmp.py
Labels: nf-testing, nf-ci

#1639 BUG: Write /Root/AcroForm in set_need_appearances_writer
  pypdf/_writer.py
Labels: is-bug

#1701 ROB: Allow more whitespace within linearized file
  pypdf/_reader.py
  tests/test_reader.py
Labels: is-robustness-issue

#1695 ENH: Support qualified names in update_page_form_field_values
  pypdf/_writer.py
  tests/test_writer.py
Labels: is-feature, workflow-forms

#1704 ENH: Extend PdfWriter.append() to pageObjects
  pypdf/_writer.py
  tests/test_writer.py
Labels: is-feature

#1729 BUG: 'DictionaryObject' object has no attribute 'indirect_reference'
  pypdf/_writer.py
  tests/test_writer.py
Labels: is-bug

#1703 ENH: Add clone_from parameter in PdfWriter constructor
  pypdf/_writer.py
  tests/test_writer.py
Labels: is-feature

#1665 ENH: Add AnnotationBuilder.popup
  docs/user/adding-pdf-annotations.md
  docs/user/annotation-popup.png
  pypdf/_writer.py
  pypdf/generic/_annotations.py
  tests/test_generic.py
Labels: is-feature, soon

#1740 ENH: Add Highlight text markup annotation
  docs/user/adding-pdf-annotations.md
  docs/user/annotation-highlight.png
  pypdf/generic/_annotations.py
  tests/test_generic.py
Labels: is-feature
