Repository py-pdf/pypdf, pull requests merged in 2023-01, with the labels that each got.

#1529 ENH: Accept hierarchical fields
  pypdf/_reader.py
  pypdf/generic/_data_structures.py
  tests/test_reader.py
Labels: is-bug, workflow-forms

#1571 DOC: Removed the redundant `fields` variable
  docs/user/forms.md
Labels: nf-documentation

#1579 TST: Unlink test output once successfully written
  tests/test_merger.py
Labels: nf-testing

#1553 ENH: Enable merging forms with overlapping names
  docs/user/merging-pdfs.md
  pypdf/_reader.py
  pypdf/_writer.py
  tests/test_reader.py
  tests/test_workflows.py
  tests/test_writer.py
Labels: workflow-forms
