Repository py-pdf/pypdf, pull requests merged in 2023-12, with the labels that each got.

#2018 ROB: Let _build_destination skip in case of missing /D key
  pypdf/_reader.py
Labels: is-robustness-issue

#2355 BUG: Handle IndirectObject as image filter
  pypdf/filters.py
Labels: workflow-images

#1945 DOC: Notes about form fields and annotations
  docs/user/forms.md
Labels: nf-documentation

#2369 DEP: Drop Python 3.6 support
  .github/workflows/github-ci.yaml
  .pre-commit-config.yaml
  .pylintrc
  Makefile
  docs/dev/testing.md
  docs/user/encryption-decryption.md
  docs/user/installation.md
  pypdf/_xobj_image_helpers.py
  pypdf/types.py
  pyproject.toml
  requirements/ci.txt
  requirements/dev.txt
  requirements/docs.in
  requirements/docs.txt
  tests/test_filters.py
Labels: breaking-change

#2375 ENH: Add Jupyter Notebook integration for PdfReader
  pypdf/_reader.py
Labels: is-feature
