Repository py-pdf/pypdf, pull requests merged in 2024-03, with the labels that each got.

#2493 DEV: add _get_page_number_from_indirect in writer
  pypdf/_writer.py
  tests/test_writer.py
Labels: PdfWriter

#2495 MAINT: Add root_object, _info and _ID to PdfReader
  pypdf/_page_labels.py
  pypdf/_protocols.py
  pypdf/_reader.py
  pypdf/_writer.py
  tests/test_writer.py
Labels: PdfReader

#2501 DOC: Minor improvements
  docs/dev/deprecations.md
  docs/dev/intro.md
  docs/dev/releasing.md
  docs/dev/testing.md
  docs/user/add-watermark.md
  docs/user/adding-pdf-annotations.md
  docs/user/merging-pdfs.md
  docs/user/reading-pdf-annotations.md
  docs/user/streaming-data.md
  docs/user/viewer-preferences.md
Labels: nf-documentation

#2504 DOC: Simplify PaperSize examples
  docs/modules/PaperSize.rst
Labels: nf-documentation

#2511 ENH: Add Enforce from PDF2.0 in viewer_preferences
  pypdf/generic/_viewerpref.py
  tests/test_writer.py
Labels: PdfWriter

#2515 DOC: Minor readability increases
  .pre-commit-config.yaml
  docs/index.rst
Labels: nf-documentation

#2521 DOC: Correct threads reference, plus minor changes
  pypdf/_reader.py
  pypdf/_writer.py
Labels: nf-documentation

#2524 TST: Improve test_get_contents_from_nullobject to show real use-case
  tests/test_page.py
Labels: nf-testing

#2505 BUG: Prevent recursive loop in some PDF files
  pypdf/_writer.py
Labels: needs-test

#2529 DOC: Update references and formatting
  docs/meta/faq.md
  pypdf/_reader.py
  pypdf/generic/_data_structures.py
Labels: nf-documentation

#2534 DOC: Update annotation list
  docs/user/reading-pdf-annotations.md
Labels: nf-documentation

#2538 MAINT: Update Read the Docs configuration
  .readthedocs.yaml
Labels: nf-documentation

#2542 DOC: Minor improvements
  docs/dev/pdf-format.md
  docs/dev/pypdf-parsing.md
  docs/user/extract-text.md
  docs/user/post-processing-in-text-extraction.md
  docs/user/streaming-data.md
Labels: nf-documentation

#2546 DOC: encryption/decryption: clone document instead of copying all pages
  docs/user/encryption-decryption.md
Labels: nf-documentation

#2549 MAINT: Fix typos found by codespell
  CHANGELOG.md
  docs/meta/changelog-v1.md
  docs/meta/taking-ownership.md
  docs/modules/PdfDocCommon.md
  docs/user/add-watermark.md
  docs/user/cropping-and-transforming.md
  docs/user/forms.md
  docs/user/pdfa-compliance.md
  docs/user/suppress-warnings.md
  pypdf/_doc_common.py
  pypdf/_merger.py
  pypdf/_page.py
  pypdf/_text_extraction/_layout_mode/_text_state_manager.py
  pypdf/_writer.py
  pypdf/_xobj_image_helpers.py
  pypdf/filters.py
  pypdf/generic/__init__.py
  pypdf/generic/_data_structures.py
  tests/test_encryption.py
  tests/test_filters.py
  tests/test_page.py
  tests/test_reader.py
  tests/test_utils.py
  tests/test_workflows.py
  tests/test_writer.py
Labels: nf-documentation

#2500 DEV: Release using the REL commit instead of git tag
  .github/workflows/release.yaml
Labels: nf-packaging

#2554 DEV: Add REL to known PR prefixes
  .github/scripts/check_pr_title.py
Labels: nf-ci

#2492 DEV: Fix changelog generator regarding whitespace and handling of "Other" group
  make_release.py
  tests/scripts/test_make_release.py
Labels: nf-packaging
