Repository py-pdf/pypdf, pull requests merged in 2024-02, with the labels that each got.

#2462 DEV: Fix changelog for UTF-8 characters
  make_release.py
  tests/scripts/__init__.py
  tests/scripts/data/commits__version_4_0_1.json
  tests/scripts/test_make_release.py
Labels: nf-packaging

#2479 DOC: Amend robustness documentation
  docs/user/robustness.md
Labels: nf-documentation

#2387 BUG: missing error on name without leading /
  pypdf/_writer.py
  pypdf/annotations/_markup_annotations.py
  pypdf/generic/_base.py
  tests/test_generic.py
Labels: breaking-change

#2481 TST: Fix benchmark failures
  tests/bench.py
Labels: nf-testing

#2482 MAINT: Remove reference to old 2.0.0 branch
  .github/workflows/github-ci.yaml
Labels: nf-ci

#2483 MAINT: Remove user assignment for feature requests
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: Meta

#2488 DOC: Improve lossless compression example
  docs/user/file-size.md
Labels: nf-documentation
