Repository py-pdf/pypdf, pull requests merged in 2024-01, with the labels that each got.

#2376 MAINT: Return None instead of -1 when page is not attached
  pypdf/_page.py
  pypdf/_reader.py
  tests/test_page.py
  tests/test_reader.py
Labels: breaking-change

#2388 ENH: Add "layout" mode for text extraction
  docs/user/extract-text.md
  pypdf/_cmap.py
  pypdf/_page.py
  pypdf/_text_extraction/__init__.py
  pypdf/_text_extraction/_layout_mode/__init__.py
  pypdf/_text_extraction/_layout_mode/_fixed_width_page.py
  pypdf/_text_extraction/_layout_mode/_font.py
  pypdf/_text_extraction/_layout_mode/_font_widths.py
  pypdf/_text_extraction/_layout_mode/_text_state_manager.py
  pypdf/_text_extraction/_layout_mode/_text_state_params.py
  resources/010-pdflatex-forms.txt
  resources/AEO.1172.layout.rot180.txt
  resources/AEO.1172.layout.txt
  resources/Claim Maker Alerts Guide_pg2.layout.txt
  resources/Epic.Page.layout.txt
  resources/multicolumn-lorem-ipsum.txt
  resources/toy.layout.txt
  resources/toy.pdf
  tests/example_files.yaml
  tests/test_text_extraction.py
  tests/test_workflows.py
  tests/test_writer.py
Labels: is-feature

#2406 BUG: PdfWriter.add_uri was setting the wrong type
  pypdf/_writer.py
Labels: is-bug
